import streamlit as st
from st_pages import Page, show_pages
from database.db_utils import DBManager
from modules.config_manager import PAGE_CONFIG

# Initialize Streamlit
st.set_page_config(**PAGE_CONFIG)

# Setup site structure
show_pages([
    Page("app.py", "Home", "🎃"),
    Page("pages/login.py", "Login", "💫"),
    Page("pages/my_account.py", "My Account", "🦱"),
    Page("pages/daily_entry.py", "Daily Entry", "✒️"),
    Page("pages/weekly_summary.py", "Weekly Summary", "📃"),
    Page("pages/monthly_summary.py", "Monthly Summary", "📰"),
    Page("pages/yearly_summary.py", "Yearly Summary", "📖"),
])

# Page content
st.title("Daily Journal App")
st.markdown("Welcome to the Daily Journaling app JournAI!\n\n"
            "To start filling in your Journal:\n\n"
            "1. Go to the login page and Register (Google OAuth will be supported... sometime in the "
            "future)\n"
            "2. Go to 'My Account'\n"
            "3. Add the questions you want to answer daily\n"
            "4. Add your OpenAI API Key\n\n"
            "You're Ready! Now you can head to the 'Daily Entry' page and start filling out or editing "
            "your daily entries!\n\n"
            "At the end of each week on Sunday, you can get a weekly summary for each of your questions "
            "generated by ChatGPT, which you can later refine with more instructions, or modify the "
            "summary itself by hand.\n")

try:
    db_manager = DBManager()
    st.success("Successfully connected to DB")
except Exception as e:
    st.error("Error while initializing DB")
    st.code(str(e))

